### ISSUE TITLE
Closed issues tracking the multi-chain

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#2053]
There are a number of remaining open issues, but these are completed.

- [x] Closed Issues
  - [x] rpc must follow chain to valid RPC (with tracing!)
  - [x] we should force the user to tell us the chain id when the add a new chain and then 
  - [x] check it against the RPC we get if it's new and we've never seen it before. Save
  - [x] that info away so we don't have to do the same every command
  - [x] `chifra init --chain unknown_chain` should fail gracefully
  - [x] Create a different Pinata account for each chain: gnosis.unchainedindex.io, etc.
  - [x] What about the bytzantium hard fork -- is there block number specific behaviour? (probably -- for ETC for example)
  - [x] What about 'status' on pre-byzantium receipts on non-main net chains?
  - [x] Should be use `v1`? Not sure.
  - [x] Don't really like it, but would allow upgrades.
  - [x] Should there be upgrades? Doesn't `manifest.txt` allow for inifinite upgrades?
  - [x] How does the server handle `--chain` and/or a different default chain? (Just works!)
  - [x] When running against remote gnosis server, our app does not send in the --client parameter (does now)
  - [x] You have to start the server with --client gnosis (or use default but client now also sends)
  - [x] The server does not accept a --chain value. Why?
  - [x] The API must accept --chain
  - [x] The server wants to run against the base configuration (i.e. mainnet -- why???). 
  - [x] What if we wanted to run two servers -- one for each of two different chains? (JUST WORKS!)
  - [x] This is another reason why --chain must be a global option.
  - [x] Otherwise, we would have to run multiple servers. As a result -- we want to disable 
  - [x] the `--chain` option for `chifra serve` (probably other things as well)
  - [x] TrueBlocks and other config file
  - [x] Should it have any per-chain data (probably not) (NO)
  - [x] Need to be able to 'merge' toml files so we can have top-level settings and per-chain overlay (Viper makes this easy)
  - [x] Don't expose IndexPath and CachePath (or any config settings) directly.
  - [x] User provides his/her own chain id. We query the chain at the RPC and verify we're connected to the rigth chain
  - [x] Config items should be able to be read from top-level and overlaid with chain specific config
  - [x] If a new chain is presented, create it under the valid `config`, `cache`, and `index` folders - i.e. establish
  - [x] Test with chifra status --chain shit
  - [x] If the config, cache, or index path does not exist, fail without proceeding if it's not the default otherwise create it
  - [x] If the config, cache, or index path does exist, establish its subfolders
  - [x] Test XDG varables somehow
  - [x] Add test cases for XDG both valid and not valid
  - [x] If the path comes from XDG it must both exist and be fully resolved, otherwise fail
  - [x] If the path contains `cache` or `unchained` or end with one one of the caches or index folders
  - [x] The prefund values per chain are in the repo but not being used
  - [x] We need to use the `--chain` option when building paths
  - [x] Rename all path routines from `getXXXPath` to `getPathToXXX` so we can find them more easily
  - [x] Put all the path related functions in a single file to better control them (one for .go, one for .cpp)
  - [x] Concentrate all changes to paths in the golang code, and send environment varaibles (current) or command line options 
  - [x] (if needed) to cary paths to the C++ code.
  - [x] Add `[settings]chain=` option to trueBlocks.toml [No -- we don't want to do this. `--chain` is a command
  - [x] line option only with `main net` the default in absences of that option.]
  - [x] Make sure the three base routines that return paths return paths ending with '/' (dependant routines already do this).
  - [x] Add a global command line option `--chain`
  - [x] Use XDG spec for environment variables
  - [x] Expand performance testing to include chain (set to `main net` for all records)
  - [x] Add chain and network/chainid to meta data
  - [x] We need to fix the install files. XDG is present, but does it work?
  - [x] Make sure blockScrape.toml is in the correct location after install
  - [x] Block Scraper
  - [x] The function init Config() in blaze needs attention vis-a-vi paths (we should be able to use the chifra paths directly)
  - [x] Blaze has command line options to explicitly take the paths
  - [x] We should be able to remove the 'requires' options (tracing, parity -- balances already removed) in blockScrape.toml
  - [x] `chifra explore` needs to be per chain

**Comment by tjayrush** [comment]
- [x] pricing w/ UniSwap
  - [x] Uniswap pricing of reconciliations obviously doesn't work on non-main net.
  - [x] `chifra when` is per chain - can we test this? Would need time stamp from multiple chains
  - [x] `ethslurp` won't work per chain.  The Etherscan API needs to be adjusted per chain
  - [x] `chifra init` doesn't currently work per chain.  There is no manifest.
