### ISSUE TITLE
Checklist for caching

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#3024]
- [x] 1. It must be versioned and allow migrations
- [x] 2. Every object that we query from the node (or any API) should be cachable
- [x] 3. Slices and Maps of these objects should be cachable with nearly no additional work
- [x] 4. The caching code for each object should be auto-generated (to make sure it easily keeps up with the docs and model code)
- [x] 5. I'm not sure if we cache the raw data only (we need the cache to be able to avoid API calls)
- [x] 6. Only fully complete, immutable items are cached (in other words, we never have to wonder if something in the cache is missing something)
- [x] 7. Articulation is a weird case. For example, an address could have no ABI available one day and yes an ABI the next. If we can "no ABI" that's not correct
- [x] 8. Names are a special cache because they are editable
- [x] 9. It would be wonderful if we had a plan for "sharding and sharing", but that's not a requirement
- [x] 10. Fast
- [x] 11. No bigger than C++ cache. Smaller if possible but not at the expense of speed (Speed first, size second)
- [x] 12. It would be excellent if other processes could read the cache directly with little effort. (A database format? A GoLang package?)

**Comment by tjayrush** [comment]
**Dawid's comments:**

It seems like 8 is a use case for cache invalidation (--decache?).

Regarding 12, we'll need a package to read from/write to cache, so it could be imported by any other app (even if it's pkg/types )

**Comment by tjayrush** [comment]
**Some notes on gob**

The docs say, "A stream of gobs is self-describing. Each data item in the stream is preceded by a specification of its type, expressed in terms of a small set of predefined types."

Translation: This is exactly what the C++ code does with it's header field. I said earlier that we don't want to 'parse' the data, but a more refined way to say that would be "we don't want to parse the data any more than we already do."

The docs say, "Pointers are not transmitted, but the things they point to are transmitted; that is, the values are flattened."

This is how it has to work, of course. (Pointers don't translate when sent over a wire.) Our C++ code also flattens pointers which are "reconstituted" upon reading. Our data does have pointers (for example, `SimpleTransaction` has a pointer to `SimpleReceipt`), but this if fine since we store `SimpleReceipt` inside of `SimpleTransaction` anyway. I feel like we may have to do something special so `SimpleBlock` doesn't store its array of transactions, but we can discuss this.

The docs say that recursive structures are okay as long as they are not cyclical. I don't think we have any cyclical data structures (ABIs?). The C++ code did have "backPointers" (for example, the Receipt had a pointer to it's containing Transaction), but I don't think our Go code has that (yet). Those "backPointers" can be assigned after the reading, though.

Edit: See performance testing below...

**Comment by tjayrush** [comment]
**From Dawid:**

```
BenchmarkGobWrite-12           1000000000             0.0001348 ns/op           0 B/op           0 allocs/op
BenchmarkGobRead-12            1000000000             0.0002373 ns/op           0 B/op           0 allocs/op
BenchmarkCustomWrite-12        1000000000             0.0000253 ns/op           0 B/op           0 allocs/op
BenchmarkCustomRead-12         1000000000             0.0000222 ns/op           0 B/op           0 allocs/op
```

our cache.Read* and cache.Write* functions are way faster than GOB

**Edit:** Nearly a 10 fold increase for our existing cache code

**Comment by tjayrush** [comment]
- [ ] 14. Some fields won't be able to be cached. For example, the block structure used to have an `age` field which changes over time. There may be other examples. Since they can only be calculated, they shouldn't be cached.
- [ ] 15. A very simple way to implement Migration for each type is `func (s *SimpleWhatever) Migrate(w *Writer) error { return s.Read(w) == nil && s.Write(w) == nil }` or similar.
